### PR TITLE
add Content-Type header to avoid warnings in ES v5.3.0

### PR DESCRIPTION
**Pull request by cinhtau**
see [Content Type](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_content_type_auto_detection)

### CODE REVIEW

**Comment by cinhtau** [comment]
Any Updates? Is elastic too busy for reviewing simple pull requests?

**Comment by keppi2** [comment]
Is there any solution for that?
We used that plugin but after upgrade of elastic we now can not use it anymore...

**Comment by cinhtau** [comment]
@keppi2 Well this project is unmaintained. We started to clone and made necessary changes ourselves.

**Comment by cinhtau** [comment]
Project unmaintained

**Pull request closed without merging**
