### PR TITLE
add username/password config option to builder

### PR DESCRIPTION
**Pull request by CrystalMethod**
In order to allow the user to use Http BasicAuth I've extended the builder.

### CODE REVIEW

**Comment by spinscale** [comment]
looks good! Would like to get it in. Can you also add a test? And, have you signed the CLA at https://www.elastic.co/contributor-agreement

**Comment by spinscale** [comment]
let's stick with java7 for 2.x releases... an alternative might be to copy the base64 class over from elasticsearch until we switch to java8

**Comment by CrystalMethod** [comment]
@spinscale Exactly, I wanted to avoid further dependencies. I will try to add a test. The CLA should be signed.

**Comment by rikcarve** [comment]
What's the current state of this pull request? We would really love to see this merged soon :-)

**Comment by CrystalMethod** [comment]
I'm not sure how to test this:

1) the embedded elasticsearch mode doesn't support basic auth
2) basic auth plugins are not quite easy to install in embedded mode (if possible at all)

I could try to implement a simple HTTP proxy with basic auth support. Any ideas?

**Comment by MaxFichtelmann** [comment]
For base64 encoding in Java 6/7 you could use `javax.xml.bind.DatatypeConverter.printBase64Binary(byte[])` to avoid using internal API

**Comment by gsmachado** [comment]
@CrystalMethod: test using [WireMock](http://wiremock.org). I think that's the best choice.

BTW: @spinscale, any idea when you could integrate this pull request? I think a bunch of people would like to have this feature.

**Pull request closed without merging**
